#!/usr/bin/env bash
 
#*=================================================================================================
#* Script Name: Oracle-JavaJRE-8_uninstall
#* Created:
#* Author:
#*=================================================================================================
#* Purpose: Remove Java JRE 8 pluging and preference panel for JRE 
#*=================================================================================================
 
#*=================================================================================================
#* REVISION HISTORY
#*=================================================================================================
#* Date:
#* Author:
#* Issue: First version of script
#* Solution:
#*=================================================================================================
 
#*=================================================================================================
#* Exit Codes
#*=================================================================================================
#* Exit 0: Sucessful unintsall of Java or Java is not installed
#* Exit 1: Java enable.plist perisists after uninstall attempt
#*=================================================================================================
 
 

  
#*=================================================================================================
#*  Global Variables
#*=================================================================================================

NOT_INSTALLED="Java JRE is Not installed"
SEARCH_FOR_VERSION="8"
RESULT=""
 
#*=================================================================================================
#*  Identify if Java is installed. If Java is installed report the version, if not exit
#*=================================================================================================
if [ -f "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Enabled.plist" ] ; then
                RESULT=$( /usr/bin/defaults read "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Enabled.plist" CFBundleVersion )
                REPORTED_MAJOR_VERSION=`/bin/echo "$RESULT" | /usr/bin/awk -F'.' '{print $2}'`
                REPORTED_MINOR_VERSION=`/bin/echo "$RESULT" | /usr/bin/awk -F'.' '{print $3}'`
                if [ "$REPORTED_MAJOR_VERSION" != "$SEARCH_FOR_VERSION" ] ; then
                                    RESULT="$NOT_INSTALLED"
                else
                                    RESULT=1."$REPORTED_MAJOR_VERSION".$REPORTED_MINOR_VERSION
                fi
else
                RESULT="$NOT_INSTALLED"
                Echo "Java is not installed"
                exit 0
fi

#*=================================================================================================
#*  If Java version is reported, remove Java files to uninstall Java per Oracle documentation
#*=================================================================================================
 
/bin/echo "Java $RESULT installed"
 
/bin/echo "Uninstalling Java"
 
 
                sudo rm -frv /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin 
                sudo rm -frv /Library/PreferencePanes/JavaControlPanel.prefPane 
 
#*=================================================================================================
#* Check to see if Java is still installed. 
#* If Java is not found script exits with a success. If Java is found script exits with a failure. 
#*=================================================================================================

if [ -f "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Enabled.plist" ] ; then
                Confirm_RESULT=$( /usr/bin/defaults read "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Enabled.plist" CFBundleVersion )
                Confirm_REPORTED_MAJOR_VERSION=`/bin/echo "$Confirm_RESULT" | /usr/bin/awk -F'.' '{print $2}'`
                Confirm_REPORTED_MINOR_VERSION=`/bin/echo "$Confirm_RESULT" | /usr/bin/awk -F'.' '{print $3}'`
                if [ "$Confirm_REPORTED_MAJOR_VERSION" != "$Confirm_SEARCH_FOR_VERSION" ] ; then
                                    RESULT="$Confirm_NOT_INSTALLED"
                else
                                    Confirm_RESULT=1."$Confirm_REPORTED_MAJOR_VERSION".$Confirm_REPORTED_MINOR_VERSION
                                    exit 1
                fi
else
                RESULT="$Confirm_NOT_INSTALLED"
                Echo "Java has been uninstalled"
                exit 0
fi
